# Generated by Django 4.2.11 on 2026-06-18 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='粮食品类名称')),
                ('safe_temp_min', models.FloatField(default=10.0, verbose_name='安全温度下限(℃)')),
                ('safe_temp_max', models.FloatField(default=25.0, verbose_name='安全温度上限(℃)')),
                ('safe_humidity_min', models.FloatField(default=50.0, verbose_name='安全湿度下限(%)')),
                ('safe_humidity_max', models.FloatField(default=75.0, verbose_name='安全湿度上限(%)')),
                ('mold_sensitivity', models.FloatField(default=1.0, help_text='数值越大越容易霉变', verbose_name='霉变敏感性系数')),
                ('pest_sensitivity', models.FloatField(default=1.0, help_text='数值越大越容易生虫', verbose_name='虫害敏感性系数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '粮食品类',
                'verbose_name_plural': '粮食品类',
                'db_table': 'grain_type',
            },
        ),
        migrations.CreateModel(
            name='Granary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='粮仓编号')),
                ('name', models.CharField(max_length=100, verbose_name='粮仓名称')),
                ('capacity', models.FloatField(default=0.0, verbose_name='设计容量(吨)')),
                ('current_stock', models.FloatField(default=0.0, verbose_name='当前库存(吨)')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='位置')),
                ('ventilation_status', models.CharField(choices=[('closed', '关闭'), ('natural', '自然通风'), ('mechanical', '机械通风')], default='closed', max_length=20, verbose_name='通风状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('grain_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granaries', to='storage.graintype', verbose_name='储粮种类')),
            ],
            options={
                'verbose_name': '粮仓',
                'verbose_name_plural': '粮仓',
                'db_table': 'granary',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VentilationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('ventilation_type', models.CharField(choices=[('natural', '自然通风'), ('mechanical', '机械通风')], max_length=20, verbose_name='通风类型')),
                ('operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人')),
                ('before_temp', models.FloatField(blank=True, null=True, verbose_name='通风前温度(℃)')),
                ('before_humidity', models.FloatField(blank=True, null=True, verbose_name='通风前湿度(%)')),
                ('after_temp', models.FloatField(blank=True, null=True, verbose_name='通风后温度(℃)')),
                ('after_humidity', models.FloatField(blank=True, null=True, verbose_name='通风后湿度(%)')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('granary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventilation_logs', to='storage.granary', verbose_name='粮仓')),
            ],
            options={
                'verbose_name': '通风记录',
                'verbose_name_plural': '通风记录',
                'db_table': 'ventilation_log',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assess_date', models.DateField(verbose_name='评估日期')),
                ('mold_risk_score', models.FloatField(default=0.0, verbose_name='霉变风险评分(0-100)')),
                ('pest_risk_score', models.FloatField(default=0.0, verbose_name='虫害扩散风险评分(0-100)')),
                ('ventilation_factor', models.FloatField(default=1.0, verbose_name='通风系数')),
                ('overall_risk_score', models.FloatField(default=0.0, verbose_name='综合风险评分(0-100)')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='low', max_length=20, verbose_name='风险等级')),
                ('is_formal', models.BooleanField(default=False, verbose_name='是否正式结论')),
                ('consecutive_days', models.IntegerField(default=0, verbose_name='连续监测天数')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processed', '已处理')], default='pending', max_length=20, verbose_name='处理状态')),
                ('disposal_suggestion', models.TextField(blank=True, null=True, verbose_name='处置建议')),
                ('disposal_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='处置人')),
                ('disposal_date', models.DateField(blank=True, null=True, verbose_name='处置日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('granary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='storage.granary', verbose_name='粮仓')),
            ],
            options={
                'verbose_name': '风险评估',
                'verbose_name_plural': '风险评估',
                'db_table': 'risk_assessment',
                'ordering': ['-assess_date', '-overall_risk_score'],
            },
        ),
        migrations.CreateModel(
            name='PestInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspect_date', models.DateField(verbose_name='检查日期')),
                ('pest_density', models.FloatField(verbose_name='虫害密度(头/公斤)')),
                ('pest_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='虫害种类')),
                ('sample_points', models.IntegerField(default=5, verbose_name='取样点数')),
                ('inspector', models.CharField(blank=True, max_length=50, null=True, verbose_name='检查人')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('granary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_inspections', to='storage.granary', verbose_name='粮仓')),
            ],
            options={
                'verbose_name': '虫害抽检记录',
                'verbose_name_plural': '虫害抽检记录',
                'db_table': 'pest_inspection',
                'ordering': ['-inspect_date'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureHumidityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('temperature', models.FloatField(verbose_name='温度(℃)')),
                ('humidity', models.FloatField(verbose_name='相对湿度(%)')),
                ('recorder', models.CharField(blank=True, max_length=50, null=True, verbose_name='记录人')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('granary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='th_logs', to='storage.granary', verbose_name='粮仓')),
            ],
            options={
                'verbose_name': '温湿度记录',
                'verbose_name_plural': '温湿度记录',
                'db_table': 'temperature_humidity_log',
                'ordering': ['-record_date'],
                'unique_together': {('granary', 'record_date')},
            },
        ),
    ]
