# Generated by Django 4.2.11 on 2026-06-18 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_level', models.CharField(choices=[('level1', '一级预警（红色）'), ('level2', '二级预警（橙色）'), ('level3', '三级预警（黄色）')], max_length=20, verbose_name='预警等级')),
                ('trigger_type', models.CharField(choices=[('auto', '自动触发'), ('manual', '手动触发')], default='auto', max_length=20, verbose_name='触发方式')),
                ('notify_method', models.CharField(choices=[('system', '系统消息'), ('sms', '短信通知'), ('email', '邮件通知'), ('all', '全部方式')], default='system', max_length=20, verbose_name='通知方式')),
                ('warning_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预警时间')),
                ('warning_content', models.TextField(verbose_name='预警内容')),
                ('status', models.CharField(choices=[('pending', '待处置'), ('processing', '处置中'), ('reviewing', '待复查'), ('closed', '已闭环')], default='pending', max_length=20, verbose_name='预警状态')),
                ('notified_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='被通知人')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='是否超时')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('granary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='storage.granary', verbose_name='预警粮仓')),
                ('risk_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='storage.riskassessment', verbose_name='关联风险评估')),
            ],
            options={
                'verbose_name': '预警记录',
                'verbose_name_plural': '预警记录',
                'db_table': 'warning',
                'ordering': ['-warning_time'],
            },
        ),
        migrations.CreateModel(
            name='WarningNotifyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_method', models.CharField(max_length=20, verbose_name='通知方式')),
                ('notify_target', models.CharField(max_length=200, verbose_name='通知对象')),
                ('notify_content', models.TextField(verbose_name='通知内容')),
                ('notify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知时间')),
                ('is_success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('fail_reason', models.TextField(blank=True, null=True, verbose_name='失败原因')),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_logs', to='storage.warning', verbose_name='预警')),
            ],
            options={
                'verbose_name': '预警通知记录',
                'verbose_name_plural': '预警通知记录',
                'db_table': 'warning_notify_log',
                'ordering': ['-notify_time'],
            },
        ),
        migrations.CreateModel(
            name='DisposalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('task_description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('assignee', models.CharField(max_length=100, verbose_name='处置负责人')),
                ('assigner', models.CharField(blank=True, max_length=100, null=True, verbose_name='任务分派人')),
                ('assigned_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='分派时间')),
                ('deadline', models.DateTimeField(verbose_name='要求完成时间')),
                ('priority', models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('normal', '普通')], default='normal', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('assigned', '已分派'), ('in_progress', '处理中'), ('submitted', '待复查'), ('review_failed', '复查不通过'), ('closed', '已闭环')], default='assigned', max_length=20, verbose_name='任务状态')),
                ('progress', models.IntegerField(default=0, verbose_name='处理进度(%)')),
                ('disposal_measures', models.TextField(blank=True, null=True, verbose_name='处置措施')),
                ('disposal_result', models.TextField(blank=True, null=True, verbose_name='处置结果')),
                ('disposal_attachment', models.TextField(blank=True, null=True, verbose_name='附件说明')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间')),
                ('reviewer', models.CharField(blank=True, max_length=100, null=True, verbose_name='复查人')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='复查时间')),
                ('review_opinion', models.TextField(blank=True, null=True, verbose_name='复查意见')),
                ('review_passed', models.BooleanField(default=False, verbose_name='复查是否通过')),
                ('archived_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='归档人')),
                ('archived_time', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('archive_remark', models.TextField(blank=True, null=True, verbose_name='归档备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_tasks', to='storage.warning', verbose_name='关联预警')),
            ],
            options={
                'verbose_name': '处置任务',
                'verbose_name_plural': '处置任务',
                'db_table': 'disposal_task',
                'ordering': ['-assigned_time'],
            },
        ),
        migrations.CreateModel(
            name='DisposalProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.IntegerField(verbose_name='当前进度(%)')),
                ('progress_description', models.TextField(verbose_name='进度说明')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('operate_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='storage.disposaltask', verbose_name='处置任务')),
            ],
            options={
                'verbose_name': '处置进度记录',
                'verbose_name_plural': '处置进度记录',
                'db_table': 'disposal_progress_log',
                'ordering': ['-operate_time'],
            },
        ),
    ]
