# Generated by Django 4.2.11 on 2026-06-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_allocationconfig_allocationexecution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationexecution',
            name='actual_arrival',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='actual_departure',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='driver_phone',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='estimated_arrival',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='estimated_departure',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='transporter',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='vehicle_no',
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='actual_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='实际运输成本(元)'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='actual_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='入库日期'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='actual_out_date',
            field=models.DateField(blank=True, null=True, verbose_name='出库日期'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='grain_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_executions', to='storage.graintype', verbose_name='粮食品类'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='in_operator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='入库操作人'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='in_remark',
            field=models.TextField(blank=True, null=True, verbose_name='入库备注'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='out_operator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出库操作人'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='out_remark',
            field=models.TextField(blank=True, null=True, verbose_name='出库备注'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='计划日期'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='planned_quantity',
            field=models.FloatField(default=0.0, verbose_name='计划调拨数量(吨)'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='received_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='实际入库数量(吨)'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='source_granary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_executions', to='storage.granary', verbose_name='源粮仓'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='target_granary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_executions', to='storage.granary', verbose_name='目标粮仓'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='transport_vehicle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='运输车辆'),
        ),
        migrations.AddField(
            model_name='allocationsuggestion',
            name='approval_remark',
            field=models.TextField(blank=True, null=True, verbose_name='审批备注'),
        ),
        migrations.AddField(
            model_name='allocationsuggestion',
            name='composite_score',
            field=models.FloatField(default=0.0, verbose_name='综合评分'),
        ),
        migrations.AddField(
            model_name='allocationsuggestion',
            name='distance',
            field=models.FloatField(default=0.0, verbose_name='距离(公里)'),
        ),
        migrations.AddField(
            model_name='allocationsuggestion',
            name='distance_score',
            field=models.FloatField(default=0.0, verbose_name='距离权重评分'),
        ),
        migrations.AddField(
            model_name='allocationsuggestion',
            name='estimated_benefit',
            field=models.FloatField(default=0.0, verbose_name='预估综合收益(元)'),
        ),
        migrations.AddField(
            model_name='allocationsuggestion',
            name='estimated_cost',
            field=models.FloatField(default=0.0, verbose_name='预估调拨成本(元)'),
        ),
        migrations.AddField(
            model_name='allocationsuggestion',
            name='estimated_risk_reduction',
            field=models.FloatField(default=0.0, verbose_name='预估风险降低(%)'),
        ),
        migrations.AddField(
            model_name='allocationsuggestion',
            name='estimated_turnover_improvement',
            field=models.FloatField(default=0.0, verbose_name='预估库存周转提升(%)'),
        ),
        migrations.AddField(
            model_name='allocationsuggestion',
            name='inventory_score',
            field=models.FloatField(default=0.0, verbose_name='库存权重评分'),
        ),
        migrations.AddField(
            model_name='allocationsuggestion',
            name='risk_score',
            field=models.FloatField(default=0.0, verbose_name='风险权重评分'),
        ),
        migrations.AddField(
            model_name='allocationsuggestion',
            name='source_current_inventory',
            field=models.FloatField(default=0.0, verbose_name='源仓当前库存(吨)'),
        ),
        migrations.AddField(
            model_name='allocationsuggestion',
            name='suggestion_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='建议编号'),
        ),
        migrations.AddField(
            model_name='allocationsuggestion',
            name='target_current_inventory',
            field=models.FloatField(default=0.0, verbose_name='目标仓当前库存(吨)'),
        ),
        migrations.AlterField(
            model_name='allocationexecution',
            name='actual_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='实际调出数量(吨)'),
        ),
        migrations.AlterField(
            model_name='allocationexecution',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('in_transit', '运输中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='allocationexecution',
            name='suggestion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution', to='storage.allocationsuggestion', verbose_name='关联调拨建议'),
        ),
        migrations.AlterField(
            model_name='allocationsuggestion',
            name='priority_level',
            field=models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级'),
        ),
    ]
