# Generated by Django 4.2.11 on 2026-06-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_allocationexecution_actual_arrival_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationexecution',
            name='actual_cost',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='actual_in_date',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='actual_out_date',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='grain_type',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='in_operator',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='in_remark',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='out_operator',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='out_remark',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='planned_date',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='planned_quantity',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='received_quantity',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='source_granary',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='target_granary',
        ),
        migrations.RemoveField(
            model_name='allocationexecution',
            name='transport_vehicle',
        ),
        migrations.RemoveField(
            model_name='allocationsuggestion',
            name='approval_remark',
        ),
        migrations.RemoveField(
            model_name='allocationsuggestion',
            name='composite_score',
        ),
        migrations.RemoveField(
            model_name='allocationsuggestion',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='allocationsuggestion',
            name='distance_score',
        ),
        migrations.RemoveField(
            model_name='allocationsuggestion',
            name='estimated_benefit',
        ),
        migrations.RemoveField(
            model_name='allocationsuggestion',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='allocationsuggestion',
            name='estimated_risk_reduction',
        ),
        migrations.RemoveField(
            model_name='allocationsuggestion',
            name='estimated_turnover_improvement',
        ),
        migrations.RemoveField(
            model_name='allocationsuggestion',
            name='inventory_score',
        ),
        migrations.RemoveField(
            model_name='allocationsuggestion',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='allocationsuggestion',
            name='source_current_inventory',
        ),
        migrations.RemoveField(
            model_name='allocationsuggestion',
            name='suggestion_no',
        ),
        migrations.RemoveField(
            model_name='allocationsuggestion',
            name='target_current_inventory',
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际到达时间'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='actual_departure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际出发时间'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='driver',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='司机'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='司机电话'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计到达时间'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='estimated_departure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计出发时间'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='transporter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='运输单位'),
        ),
        migrations.AddField(
            model_name='allocationexecution',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='车牌号'),
        ),
        migrations.AlterField(
            model_name='allocationexecution',
            name='actual_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='实际调拨数量(吨)'),
        ),
        migrations.AlterField(
            model_name='allocationexecution',
            name='status',
            field=models.CharField(choices=[('scheduled', '已计划'), ('loading', '装货中'), ('in_transit', '运输中'), ('unloading', '卸货中'), ('completed', '已完成'), ('cancelled', '已取消')], default='scheduled', max_length=20, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='allocationexecution',
            name='suggestion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='execution', to='storage.allocationsuggestion', verbose_name='关联调拨建议'),
        ),
        migrations.AlterField(
            model_name='allocationsuggestion',
            name='priority_level',
            field=models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('normal', '普通')], default='normal', max_length=20, verbose_name='优先级'),
        ),
    ]
